### ISSUE TITLE
Reloading the page on certain sections (add-ons, settings) un-sets some CSS until the dashboard is re-selected

### ISSUE THREAD

**Issue by csanner** [th3jesta/ha-lcars#10]
When you reload the page (or  open it for the first time) on, for example, the add-ons page, none of the CSS for the sidebard is rendered until you select the dashboard.
Additionally, the CSS does not get applied to things within the add-ons section, leaving them difficult to read at times

**Comment by th3jesta** [comment]
This is a known issue with card-mod. The custom CSS is only loaded when card-mod is loaded in the DOM, and card-mod only loads when a dashboard is loaded. Unless I am mistaken, there's no way around this unless card-mod implements one.

**Comment by csanner** [comment]
Ah this is a duplicate issue then. Interesting

**Comment by csanner** [comment]
It's likely that card-mod can't do anything about it either.

**Comment by th3jesta** [comment]
I just posted a question on the card-mod topic in the community to verify this. I thought I saw it in the documentation or an issue, but I couldn't find it to reference here. Now I'm questioning everything.

**Comment by csanner** [comment]
LOL - sounds like my life.
Feel free to close this as duplicate.
I also got errors about a bunch of duplicate lines in the css - the same ones in each file - I deleted the second of each, but I don't know which was correct.
Would you like me to open a second issue?
I'd submit a pull request but, as I said, not sure what the fix would be.

**Comment by th3jesta** [comment]
Sure, please do! I won't have much time to address anything until next week. Is it working despite the errors? Also, do you have the latest release? I fixed some duplicate errors in the latest release.
