### ISSUE TITLE
Footers and headers show up as buttons in the new 2024.8.0 update

### ISSUE THREAD

**Issue by MarioFlying** [th3jesta/ha-lcars#103]
Once I updated to the new 2024.8.0 update, LCARS footers and headers started displaying as simple buttons.
Re-selecting the theme from the theme selection menu in my home allowed them to display correctly, but they would still show up as buttons if I switched to the other lovelace views and, once the page was refreshed, even in the home view.

Once I reverted Core to 2024.7.4, footers and headers would show up correctly again.

**Comment by th3jesta** [comment]
This is a bug in card-mod. I have created this issue in the card-mod repo:
https://github.com/thomasloven/lovelace-card-mod/issues/392
