### ISSUE TITLE
custom color for footer and middle

### ISSUE THREAD

**Issue by WueBumbum** [th3jesta/ha-lcars#107]
Hello,

I may have overlooked this, but is it possible to set a custom color for footers and middles?

best regards
Andreas

**Comment by th3jesta** [comment]
Yes, using the `style` component of card-mod. Here's an example that works in some cases, though you'll have to use the inspect feature of your browser to find the right variables to change if this doesn't work for you:
```
card_mod:
  class: header
  style: |
    ha-card {
      --lcars-ui-primary: green;
    }
```

An understanding of card-mod _and_ CSS/HTML is necessary, here.
