### ISSUE TITLE
duplicate key modern light gray

### ISSUE THREAD

**Issue by VPelt** [th3jesta/ha-lcars#110]
I get the following warning in my logs

`2024-09-30 12:51:23.814 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/themes/lcars/lcars.yaml contains duplicate key "lcars-modern-light-gray". Check lines 81 and 1899`

Runing LCARS 2.3.1

**Comment by th3jesta** [comment]
That is fixed in the upcoming 3.0 release. Thanks. In the meantime, it won't break anything. Just an annoying error.
