### ISSUE TITLE
Link text color always matches background color

### ISSUE THREAD

**Issue by Olli2k** [th3jesta/ha-lcars#112]
![grafik](https://github.com/user-attachments/assets/34078662-bbd0-45e0-b645-1d3c25f7f593)

Screen is just an example. For examples in notifications: There the background is black and the link text as well. Using LCARS Default lcars.yaml. But this problem may have been existing before 3.0 update, but I need a little hint for fixing this.

Thx in advance.

**Comment by th3jesta** [comment]
Well, that's dumb, isn't it?

**Comment by th3jesta** [comment]
Fixed in latest release.
