### ISSUE TITLE
styles in card_mod no longer working

### ISSUE THREAD

**Issue by Andy1910** [th3jesta/ha-lcars#113]
styles no longer working in latest update
this is the card styles no longer works

show_name: true
show_icon: true
type: button
tap_action:
  action: toggle
entity: light.lamp
icon: mdi:floor-lamp-torchiere
show_state: true
theme: LCARS Default
card_mod:
  class: button-lozenge-right
  style: |
    ha-card {
      {% if states['light.lamp'].state == 'on' %}
        {% set rgb_color = state_attr('light.lamp', 'rgb_color') %}
        background-color: rgba({{ rgb_color[0] }}, {{ rgb_color[1] }}, {{ rgb_color[2] }}, 1);
        color: black;
      {% else %}
        background-color: #dd4444;
        color: black;
      {% endif %}
    `}`

it worked perfectly in 2.3.1

**Comment by krangchen** [comment]
Hey,

I can confirm this to be true. My lcars doesn't change the button background color according to state but now looks more standard with only the outline showing the desired color but always on. Only icon changes according to state as per default behavior.

This is kind of important to me as the use of card styles allows me to use lcars even on smaller distant screens to show state infos. :)

**Comment by pciduncan76** [comment]
Same problem.

**Comment by th3jesta** [comment]
Simple fix, please use the `!important` directive wherever a style isn't being overridden. . 
```
style: |
  ha-card {
    {% if is_state('light.torchier_one', 'on') %}
      background-color: aquamarine !important;
      color: black; /* or any other logic for text color */
    {% else %}
      background-color: default;
      color: black;
    {% endif %}
  }
```

**Comment by pciduncan76** [comment]
Thanks.  Solution works perfectly!

**Comment by krangchen** [comment]
Yep, that works, thanks! :)
