### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by WolfgangFuchs** [th3jesta/ha-lcars#116]
Hello,
I'm contacting you with a question about a problem that I can't solve. 
On (almost) all devices, HA displays the layout correctly --> HA1.jpg. Only on one (iPad) the display of the weather forecast is not correct --> HA2.jpg. I've checked/tried everything but nothing has worked so far :-(( Do you perhaps have an idea/tip? Thank you in advance.

Kind regards from Cologne
wolfgang
![HA1](https://github.com/user-attachments/assets/bfc23408-d651-4211-9bef-f75b7adf5b80)
![HA2](https://github.com/user-attachments/assets/85e38820-43f3-4638-8c6f-e071d3383686)

**Comment by WolfgangFuchs** [comment]
Core - 2024.10.1
Supervisor - 2024.09.1
Operating - System 13.1
Frontend - 20241002.2

LCARS - 3.0.0

**Comment by z3r0l1nk** [comment]
Same version of HASS on both Ipad's?
Also, can you share the code?

**Comment by WolfgangFuchs** [comment]
>Same version of HASS on both Ipad's?
I think so. where can I find the version number?

Here the code:
type: vertical-stack
cards:
  - type: custom:html-card
    card_mod:
      class: header-left
    content: <h1>Allgemein</h1>
  - type: entities
    entities:
      - entity: sensor.mein_datum
      - entity: sensor.sonnenaufgang
      - entity: sensor.sonnenuntergang
      - entity: sensor.sun_solar_elevation
        name: Sonnenhöhe
    state_color: true
    card_mod:
      class: middle-left
  - show_current: true
    show_forecast: true
    type: weather-forecast
    entity: weather.forecast_home_2
    forecast_type: daily
    name: Wettervorhersage
    card_mod:
      class: middle-left
  - type: entities
    entities:
      - entity: sensor.openweathermap_weather
        name: Bewölkung
      - entity: sensor.openweathermap_cloud_coverage
        name: Bewölkung
        icon: mdi:weather-cloudy
      - entity: sensor.openweathermap_humidity
        name: Luftfeuchtigkeit
      - entity: sensor.openweathermap_pressure
        name: Luftdruck
      - entity: sensor.openweathermap_rain
        name: Regen
      - entity: sensor.openweathermap_visibility
        name: Sichtweite
      - entity: sensor.openweathermap_wind_speed
        name: Wind
      - entity: sensor.openweathermap_wind_bearing
        name: Windrichtung
    card_mod:
      class: middle-left
  - type: custom:html-card
    card_mod:
      class: footer-left
    content: " "

**Comment by z3r0l1nk** [comment]
I don't know how you can see the version on iPad or iPhone.
Regarding the code i don't see any issue.
Maybe anyone else has any ideas for this problem?

**Comment by th3jesta** [comment]
This is an issue with card-mod and the default HA weather card. There is nothing I can do to fix it, BUT there is a better weather card in HACS that works perfectly. :)

https://github.com/bramkragten/weather-card

**Comment by WolfgangFuchs** [comment]
Thank you very much for the good tip!
