### ISSUE TITLE
LCARS doesn't work anymore with up to date Home Assistant

### ISSUE THREAD

**Issue by Gherry777** [th3jesta/ha-lcars#119]
Hi,
I was just playing around trying to create a nice LCARS Dashboard and I found out this bug:
I type some correct code, the preview is as I expected, then when I save the card, the actual output is different.

Rebooting doesn't fix the issue.

I'll attach a short video to show you what I mean.
Everything is up to date, anyway these are the version I'm using.
Core 2024.10.2
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.3
LCARS 3.0.0

https://github.com/user-attachments/assets/37e2157e-c147-4527-ad6d-63aaeb5b1c7b

**Comment by Crefelder** [comment]
Same problem here: only the classes: middle-left, middle-right & middle-contained are working. 
But no header or footer classes in combination with type: markdown. I also can see that it is sometimes working in preview window at typing YAML. But after saving, only in rare cases and after reloading the page it is gone.
If you use another type than "markdown" the footer & header classes are working, but that is what nobody needs ;)

**Comment by Crefelder** [comment]
I found out get it working with type:custom:html-card but not type:markdown.
<img width="756" alt="image" src="https://github.com/user-attachments/assets/ea36b194-ba0c-46bc-b4b1-84fb8afc3ed8">
<img width="378" alt="image" src="https://github.com/user-attachments/assets/a95d8f8a-1e45-4ab7-9880-3b98acb01527">

**Comment by th3jesta** [comment]
What bad luck! You've chosen the two cards that no longer work reliably with card-mod! 

Unfortunately, this is a card-mod problem and not something I can fix:
https://github.com/thomasloven/lovelace-card-mod/issues/392
https://github.com/thomasloven/lovelace-card-mod/issues/386

Fortunately, there are alternative cards to do the same kinds of things:
- To replace markdown card: https://github.com/PiotrMachowski/lovelace-html-card
- To replace the weather card: https://github.com/bramkragten/weather-card

weather-card is a much better option in my opinion anyway.

**Comment by Gherry777** [comment]
Thank you.
I'll try to replace cards, unfortunately I'm not really good at this, so I'll probably end up waiting for a guide or updated instructions from someone!

LCARS is great, thank you for your work.
