### ISSUE TITLE
Feature: paper-tab tabs square to fit with horizontal lcars bars

### ISSUE THREAD

**Issue by csanner** [th3jesta/ha-lcars#13]
I've got the code for this but I wanted to see if you were interested in it before submitting the pull request.

I also figured out how to make the selected section a different color from the rest

**Comment by th3jesta** [comment]
Absolutely interested. Please submit a PR with some screenshots and we can go from there.

**Comment by csanner** [comment]
![Screenshot_20230102_123452](https://user-images.githubusercontent.com/1806131/211883283-2b3811ea-7b04-411b-93c5-81b3c0e828c0.png)

Here's a screenshot that shows the code I've got

**Comment by th3jesta** [comment]
Oh my, that's way better than what I was planning in #23. If you want to just share the CSS here, I can work on integrating it.

**Comment by th3jesta** [comment]
Merged into master, no release yet. 
It looks great! Good call on the tertiary selected color. Not sure why that never struck me as a good idea! I may tweak the black borders a tiny bit before release. Thanks so much!

**Comment by th3jesta** [comment]
Adjusted the gaps, and and also pulled your idea on tertiary for selected. 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/38670315/211900114-3cd6abc6-4b86-4dc6-85ea-16a79a4c75ab.png">
Released in https://github.com/th3jesta/ha-lcars/releases/tag/HA-LCARS-1.8
