### ISSUE TITLE
Clock not displaying for non-admin user

### ISSUE THREAD

**Issue by mijofa** [th3jesta/ha-lcars#17]
Title says it all really.
It works fine for the administrator user, but I mostly want this theme for an Android kiosk-like device or 2 around the house, and I don't really want them set up with administrator users.

I see a little bit of blue where the clock would be, but it's less than a digit wide and there's no actual time displayed.

**Comment by th3jesta** [comment]
I am able to reproduce. It is related to the permissions to edit a dashboard. Adding to the backlog.

**Comment by th3jesta** [comment]
Please try updating to release HA-LCARS-1.7.4 and let me know.

**Comment by mijofa** [comment]
Heh, I suspected something like that would be the cause, works great now, thanks! :)
