### ISSUE TITLE
Markdown elements mostly only work as header

### ISSUE THREAD

**Issue by mijofa** [th3jesta/ha-lcars#19]
Here's a screenshot that shows it better than I can really describe:
![HA-lcars-markdown-class-weirdness](https://user-images.githubusercontent.com/4810578/210453469-56e9c8fa-5ec2-4398-9c52-e27c68a8a618.png)

Note the border-radius in the top-left of all but the middle one.
It looks like it's coming from the 'ha-markdown.no-header' element, when I unset the border-radius on that element in the browser's inspector, it removes that rounded corner for all of them, including the actual header one, even though it does seem to be set properly on the parent ha-card.header element.
I was struggling to find a solve for this using the inspector, but I'm not well versed in CSS styling.

**Comment by thedeedubyah** [comment]
I've found the same issue. A work-around is to manually set the border-radius using card_mod, e.g.

```
type: markdown
content: your content here
card_mod:
  class: footer
  style: |
    ha-markdown {
       border-radius: 0 0 0 20px !important;
    }
```

**Comment by th3jesta** [comment]
Thanks for the footwork, folks. 

I was able to implement some global fixes so that Markdown should look good in all situations.

**Comment by mijofa** [comment]
Confirmed that's much better now, thanks for the speedy fix
