### ISSUE TITLE
Add bottom margin and highlight color to dashboard tabs

### ISSUE THREAD

**Issue by th3jesta** [th3jesta/ha-lcars#23]
The selected tab has no background, and the tabs all sit on the bottom of the header. Lazy slobs. 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/38670315/210630697-92e9b123-94cc-471d-ba48-a8f77debbf6e.png">

**Comment by csanner** [comment]
I've got code that will fix this but I haven't had a chance to clean it up for submission, since it's in my custom code on my HA instance and my fork doesn't connect to that...
