### ISSUE TITLE
Footer-right has sharp angle on inside of curve

### ISSUE THREAD

**Issue by mermelmadness** [th3jesta/ha-lcars#24]
![image](https://user-images.githubusercontent.com/38080873/210636620-432d45c9-1d81-49f3-91d1-f1d8e05e47d9.png)

**Comment by th3jesta** [comment]
Acknowledged. Thanks.

**Comment by th3jesta** [comment]
Regression from https://github.com/th3jesta/ha-lcars/issues/19

**Comment by th3jesta** [comment]
Fixed in HA-LCARS-1.7.7
