### ISSUE TITLE
Font doesn't translate to all menus

### ISSUE THREAD

**Issue by mermelmadness** [th3jesta/ha-lcars#26]
![image](https://user-images.githubusercontent.com/38080873/210658199-ba6eb99b-08bf-4ceb-ac78-f3892ac2fc03.png)
![image](https://user-images.githubusercontent.com/38080873/210658222-c5fc9e6d-1e96-45c5-b129-1e1378714744.png)

**Comment by th3jesta** [comment]
This is a known issue with `card-mod` and outside of my ability to fix. It is implicitly included in the **Known issues** portion of the readme.

**Comment by mermelmadness** [comment]
Pshh.  Who actually reads the README?

j/k  Thanks

**Comment by th3jesta** [comment]
> Pshh. Who actually reads the README?
> 
> j/k Thanks

I don't. :p
