### ISSUE TITLE
Create right-handed lozenge and bullet classes

### ISSUE THREAD

**Issue by Xiondewah** [th3jesta/ha-lcars#27]
If it's possible, the following would be useful:

a right-hand lozenge button
A header/footer (handed, as currently) where you didn't have to enter any content (you may already know a way to do this?

Loving it so far - currently moving stuff over so I can start turning off other dashboards.

**Comment by th3jesta** [comment]
Regarding the header and footer, that would require creating a custom card type which would fall outside the theme. Instead I found this workaround that should work for you:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/38670315/210792013-48d5f5fc-b6fa-42bd-bbaf-a3169ea5e5d1.png">
Just add this text to the content of a Markdown card: `## &nbsp;`
I'll add this as a tip in the readme.

**Comment by Xiondewah** [comment]
Brilliant - thanks.


Jonathan

On 5 Jan 2023, at 13:35, Jesse Wisener ***@***.***> wrote:

﻿

Regarding the header and footer, that would require creating a custom card type which would fall outside the theme. Instead I found this workaround that should work for you:
[image]<https://user-images.githubusercontent.com/38670315/210792013-48d5f5fc-b6fa-42bd-bbaf-a3169ea5e5d1.png>
Just add this text to the content of a Markdown card: ## &nbsp;
I'll add this as a tip in the readme.

**Comment by csanner** [comment]
pull request submitted with right-hand lozenge & bullet buttons

**Comment by th3jesta** [comment]
@csanner requires a beer.
