### ISSUE TITLE
Feature: Possibility to deactivate clock and mobile layout

### ISSUE THREAD

**Issue by sgofferj** [th3jesta/ha-lcars#33]
THANK YOU for this great theme! I have been waiting forever for a really good LCARS theme!

My HA UI is organized so that every user has their own dashboard and the dashboards have multiple views. On my mobile device, the clock takes so much space that the dashboard is almost unusable.

![Screenshot_20230110-104708](https://user-images.githubusercontent.com/3258466/211507725-f4ebe6bb-d08a-4113-a494-3772de7ecac1.png)

I would like to suggest adding an option which disables the clock either completely or when the screen is narrower than x.

**Comment by csanner** [comment]
I would LOVE to figure out how to do this.
I was looking at some CSS properties but I'm not sure how to apply them in HA - 

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Conditional_Rules#:~:text=CSS%20Conditional%20Rules%20is%20a,sheet%20is%20being%20applied%20to.

**Comment by csanner** [comment]
I strongly suspect this is directly related to https://github.com/th3jesta/ha-lcars/issues/31

**Comment by th3jesta** [comment]
I swear I posted a reply to this issue days ago, but apparently I didn't hit send.

YES! I will find a way to do this as your result and experience is unacceptable to me. The way to do this will be to hijack the existing @media queries that Home Assistant is already using to manage the layout at different resolutions, which is the standard for responsive web design. I'm just not sure how to target them with card-mod at the moment.

**Comment by th3jesta** [comment]
That said, I love your remote!

**Comment by th3jesta** [comment]
Fixed in [HA-LCARS-1.8.2](https://github.com/th3jesta/ha-lcars/releases/tag/HA-LCARS-1.8.2)

**Comment by csanner** [comment]
ah - it's commented out in the current release.
I uncommented both sections and it works great, but not sure which you intended to leave active

**Comment by th3jesta** [comment]
@csanner did you by chance kill and restart the app? I noticed I had to do that to get the clock to go away after the update. The commented section I think you were referring to was just something I was testing that I forgot to take out. I'd be interested in a screenshot.

**Comment by csanner** [comment]
I did. 
It's working now.
Some of these behaviors are very odd.
I'm going to open an issue about the thermostat card I'm using and some other things to track them and I'll start poking at it.
Also, I've created a couple animated gifs from some YouTube videos that are fun to stick in picture cards. Not sure about the ethics or legality of distributing those...

**Comment by sgofferj** [comment]
Thank you all!!!
