### ISSUE TITLE
Media controls volume unreadable

### ISSUE THREAD

**Issue by mijofa** [th3jesta/ha-lcars#43]
Looks like you've got white-on-white in the theme colours
![image](https://user-images.githubusercontent.com/4810578/212819675-f4a02370-68d0-461e-abb9-74e3699195ba.png)

I believe you need to change the colour of the knob [here](https://github.com/th3jesta/ha-lcars/blob/master/themes/lcars.yaml#L130) or the colour of the actual text [here](https://github.com/th3jesta/ha-lcars/blob/master/themes/lcars.yaml#L136)

I've worked around it with this style in card_mod: `ha-card{--paper-slider-font-color:black}`

**Comment by th3jesta** [comment]
Thanks for pointing this out! Check out HA-LCARS-1.8.7 to see if it resolves your issue, please.

**Comment by mijofa** [comment]
Yep, that's solved it, thanks
