### ISSUE TITLE
Font and background - same color

### ISSUE THREAD

**Issue by scaarup** [th3jesta/ha-lcars#46]
I am using the LCARS Kronos theme and when a new device is discovered in Home Assistant, the button, which normally says "configure", is just a black box:
![image](https://user-images.githubusercontent.com/8055470/214242616-0806aafe-7dba-4409-aa72-ca3b9f7044dc.png)

![image](https://user-images.githubusercontent.com/8055470/214243229-c36b35a3-e551-464c-9ce4-1c9ed8dfa7fb.png)

**Comment by th3jesta** [comment]
Thanks for the helpful screenshots!

**Comment by th3jesta** [comment]
This should be fixed in 2.0

**Comment by th3jesta** [comment]
Sorry, not fixed yet 2.1, but I have implemented and validated a fix that will ship in 2.2.
