### ISSUE TITLE
Add method to enable/disable noise and gradient textures

### ISSUE THREAD

**Issue by th3jesta** [th3jesta/ha-lcars#5]
Could be done with YAML anchors, or Home Assistant light/dark modes. Ideas are welcome.

**Comment by csanner** [comment]
I just had an idea of how to do this but I need to better understand exactly what's creating the gradient. 
What would the optimal "non-gradient" version of this look like? would I be commenting out entire classes?

**Comment by csanner** [comment]
though I suppose I could just *tell* you.
I think the best way to do this is to create a new "section" of CSS, akin to "lcars-colors" and "base" and then include or exclude it in various sub-themes.
So you'd have "LCARS Default" and "LCARS Default Gradient" as themes, one including the "gradient" section and the other, not.

**Comment by csanner** [comment]
I get that this theoretically doubles the number of themes but that's probably the right way to do it in any case.
