### ISSUE TITLE
Button color fades with light percentage

### ISSUE THREAD

**Issue by CmdreIsaacHull** [th3jesta/ha-lcars#53]
I noticed an odd thing today. When I have lights in a room that are dimmed to a level less than 100%, the button highlight color also dims the same amount. If the lights are completely off or are all at 100%, then the highlight renders normally. This is separate from the icon color. That does adjust normally.

![image](https://user-images.githubusercontent.com/93444427/215865850-053e3358-846a-4485-890e-472854a964e5.png)

**Comment by th3jesta** [comment]
This is just a "feature" of Home Assistant's UI, I think. It indicates if a light isn't at full brightness, or if a group of a lights is only partially on. I'm not too worried about this one.
