### ISSUE TITLE
1.9.2 update makes moreinfo popups unreadable

### ISSUE THREAD

**Issue by sgofferj** [th3jesta/ha-lcars#60]
The 1.9.2 update has changed the background color of the moreinfo popups which makes them pretty much unreadable.

![Screenshot_20230414_113841](https://user-images.githubusercontent.com/3258466/231992198-998b2ae0-fafa-4138-acf9-5bd2fd495a16.png)

**Comment by th3jesta** [comment]
This was a result of the mitigation for the sidebar border. I've got it and the border fixed already. Just gotta add a few more things to 2.0 to release it! A workaround is to comment out `mdc-theme-surface: var(--lcars-ui-primary)`
