### ISSUE TITLE
Configure button on MQTT integration is illegible

### ISSUE THREAD

**Issue by askpatrickw** [th3jesta/ha-lcars#62]
This picture shows what I mean.
Notice the black square on MQTT and then that the HACS tile has a readable "configure".

2023.4 Mac App
2023.5 HA

![image](https://user-images.githubusercontent.com/4002194/236648270-76235629-23ed-4b75-b09d-71b0d74cbac0.png)

**Comment by th3jesta** [comment]
I thought this was fixed in the latest release. Please verify you are on that, and if not, I'll have it for you in the next release. I'm looking at it fixed on my own instance now.

**Comment by askpatrickw** [comment]
Looks to be 2.1 to me, no updates available from HACS.

**Comment by th3jesta** [comment]
Fixed in 2.2.

**Comment by askpatrickw** [comment]
🙏 Thank you!
