### ISSUE TITLE
Sounds not constrained to theme

### ISSUE THREAD

**Issue by mtwilliams5** [th3jesta/ha-lcars#63]
When using the LCARS Sounds helper toggle, sounds are playing even when a different theme than HA LCARS is selected.

The use-case I have for this is that I use a different theme for the majority of my HA use - desktop, phones, etc - but I have an NSPanel Pro replacing the light switch in my study that I use the LCARS theme for to make it look like a door panel from the shows. The problem is, when I have the sounds toggle set to on, I am getting the LCARS sound from every other device as well that isn't using the theme.

Surely the sounds should only be loaded when the theme is in active use? I also get the "removing sidebar border" and "adding audio" messages in the console even when the toggles are off, so the script in general is just running regardless.

Digging around in the dev panel in chrome, I can see there is a "selected theme" item that could be used for checking this - though it looks to be the user's selected theme, and shows as `""` when you have 'Use backend preferred theme' set, which makes things trickier to implement without another helper option. Having a very brief dig around, there doesn't seem to be a straight-forward way to identify the current backend-selected theme, so maybe a quick and dirty solution here is to have an if statement that checks the selected theme in local storage against a regex for lcars, and then based on the state of a third toggle (lcars_backend_theme_sounds perhaps?), have it also include an empty string in that if statement?

**Comment by th3jesta** [comment]
I will work on this next with priority--once I get back from vacation.

**Comment by th3jesta** [comment]
Added in 2.2.
