### ISSUE TITLE
Large UNKNOWN text right upper corner

### ISSUE THREAD

**Issue by WeterPeter** [th3jesta/ha-lcars#64]
Nice work!

I have an issue that a large UNKNOWN text is covering the right upper corner.
![Scherm­afbeelding 2023-05-18 om 09 36 47](https://github.com/th3jesta/ha-lcars/assets/52879850/e9dc0376-ba7e-4126-abb3-98efadc9836e)

This occours with any LCARS theme except the default non-LCARS HA theme.
HA 2023.5.2

How to fix this?

**Comment by WeterPeter** [comment]
User error: I did not add the clock config in my configuration.yaml (and *restart* HA) :

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

Fixed! :-)

**Comment by askpatrickw** [comment]
@WeterPeter 

Such an existential dilemma. :-)
Prolly good to close the issue now.

**Comment by domesticatedviking** [comment]
It would be good if the UNKNOWN text were replaced with something like ??:?? for two reasons.
First, it gives the user who is unfamiliar with the UI a hint as to what is missing, and second, it won't occlude the three dot menu used for editing the interface, which I briefly found *very* frustrating.
