### ISSUE TITLE
Answer Known: Document how to host font locally

### ISSUE THREAD

**Issue by askpatrickw** [th3jesta/ha-lcars#69]
I also run HA in my "shuttle" (Ok it a van) and we sometimes don't have an internet connection. It would be ideal to be able to host the fonts locally.

I'll look into this, as well and offer a doc update when\if I figure it out, but I'm opening this Issue in case someone already has the info.

**Comment by askpatrickw** [comment]
This thread is interesting ... 
Not working for me though.

**Comment by askpatrickw** [comment]
Just to record what has been tried and what is working... 

1. I looked in the developer console and download the WOFF version of the font which was being dowloaded from google fonts. I uploaded this to `/config/www/antonio.woff2`. Attached here: [antonio.woff2.zip](https://github.com/th3jesta/ha-lcars/files/11580940/antonio.woff2.zip)
3. I created `/config/www/fonts.css` as in the thread above pointing to the `antonio.woff2` file.

```css
@font-face {
  font-family: "Antonio";
  src: url(/local/antonio.woff2) format('woff2');
}
```

4. I added the `/config/www/loadfonts.js` file as in the thread above.

```javascript
function loadcss() {
    let css = '/local/fonts.css?v=0.006'

    let link = document.createElement('link');
    let head = document.getElementsByTagName('head')[0];
    let tmp;
    link.rel = 'stylesheet';
    link.type = 'text/css';

    tmp = link.cloneNode(true);
    tmp.href = css;
    head.appendChild(tmp);
    console.info('%c Font Style sheet loaded', 'color: white; background: #000; font-weight: 700;');
}
loadcss();
```

5. I added the `/config/www/loadfonts.js` as a resource in Dashboards and remove the google font resource.

I restarted Home Assistant, used "clear cache and reload" It didn't seem to work at first, but finally it did work and all seems good now!!

I'm happy to add this to the README or we can't point people to this Issue.

**Comment by th3jesta** [comment]
> 

I don't see a thread. Link?

**Comment by th3jesta** [comment]
Also, thanks a lot for this. This will help out other shuttlecraft owners, or folks who want their Home Assistant to be air-gapped. I added a link to this issue in the Tips and Tricks section.

**Comment by askpatrickw** [comment]
The thread I didn't link

http://community.home-assistant.io/t/use-ttf-in-lovelace/143495/48

**Comment by FoxXxHater** [comment]
Hay,

I have the problem that the files wont load...
So i looks:
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/a4435682-60a8-4f75-b5e5-3723975f07ec)
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/148c95d4-b067-43b9-ac85-65bfd4630625)
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/f32794df-bc10-46b2-bbda-dc4a7573d709)

**Comment by FoxXxHater** [comment]
Chrome Console Log:
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/8413cf8f-e3f2-4720-be93-4c8d6f844758)

**Comment by th3jesta** [comment]
> Chrome Console Log: ![image](https://private-user-images.githubusercontent.com/54017453/295994531-8413cf8f-e3f2-4720-be93-4c8d6f844758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDkzMjYsIm5iZiI6MTcwNTAwOTAyNiwicGF0aCI6Ii81NDAxNzQ1My8yOTU5OTQ1MzEtODQxM2NmOGYtZTNmMi00NzIwLWJlOTMtNGM4ZDZmODQ0NzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIxMzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNWNkNzdhM2ZlOTk4NGM3ZDliZjcyZmIxZTk2MzRhZjE4MzNkOTgwZGU2MmRiY2RhZmY1NjQxZTk1MzdmODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SYv6pdbof3oAAPFR7dlN9jF8sDEH5tb1BHN6qTQL88Y)

Please ensure that the Resource you set up for `lcars.js` is of type JavaScript and not Stylesheet, as instructed: https://github.com/th3jesta/ha-lcars/blob/master/README.md#ii-add-the-font-and-javascript-file

**Comment by FoxXxHater** [comment]
Wie Sie in meinem letzten (schwarzen) Bild sehen, ist die lcas.js als Javascript-Modul eingestellt

**Comment by th3jesta** [comment]
Try replacing `/config/www` with `/local`. That is how Home Assistant refers to the `www` directory. Not sure if it will fix it, but either way, that's best practice.

**Comment by FoxXxHater** [comment]
Okay, i will try that
