### ISSUE TITLE
Malformed YAML Forces Safe Mode

### ISSUE THREAD

**Issue by mermelmadness** [th3jesta/ha-lcars#7]
Tried installing this theme and when restarting HA it booted into safe mode with the following error:

`Found duplicate anchor 'card-mod-root'; first occurrence in "/config/themes/lcars/lcars.yaml", line 357, column 18 second occurrence in "/config/themes/lcars/lcars.yaml", line 577, column 18
`

I had to delete the `lcars` folder in /config/themes/ in order to fully boot HA

**Comment by th3jesta** [comment]
Thanks for letting me know. Sorry for the inconvenience. I just released the latest updates which do not have the duplicate `card-mod-*` entries. Please update and let me know if you have further issues.

**Comment by mermelmadness** [comment]
New error:

`Mapping values are not allowed here in "/config/themes/lcars/lcars.yaml", line 28, column 66`

**Comment by th3jesta** [comment]
That's a weird one. There is no column 66 on line 28 in the yaml. I just pushed one more update just in case.

**Comment by mermelmadness** [comment]
> That's a weird one. There is no column 66 on line 28 in the yaml. I just pushed one more update just in case.

![image](https://user-images.githubusercontent.com/38080873/208332804-1a80ccc8-8897-47ba-9af7-ee7c9e1f5b04.png)

**Comment by mermelmadness** [comment]
No change.  Same error.

**Comment by th3jesta** [comment]
What file is that? That's not `lcars.yaml`.

**Comment by mermelmadness** [comment]
> What file is that? That's not `lcars.yaml`.

Maybe I'm downloading it wrong from Github.  Stand by...

**Comment by th3jesta** [comment]
You should be able to install it from HACS by adding the repo in HACS.

**Comment by mermelmadness** [comment]
Ok, I was right-clicking on the YAML and "Save Link As..." instead of downloading the source code.  My bad.  That seems to have worked, no errors when calling `frontend.reload_themes`

Thank you.

**Comment by th3jesta** [comment]
Yay!
