### ISSUE TITLE
Editing menu is broken

### ISSUE THREAD

**Issue by askpatrickw** [th3jesta/ha-lcars#70]
When you long press in the top right, you should be able to edit the navigation menu.

See screenshot below, you cannot.  

![image](https://github.com/th3jesta/ha-lcars/assets/4002194/1c97506b-cd1b-46b3-92bc-11af0972cc75)

**Comment by th3jesta** [comment]
I'm unable to reproduce this one. Can you check browser console and maybe investigate the elements and see what is amiss?
<img width="277" alt="image" src="https://github.com/th3jesta/ha-lcars/assets/38670315/2de39d22-22d2-4ca7-8c5e-5937cce98f0a">

**Comment by askpatrickw** [comment]
And now this isn't happening for me either. 🤷‍♂️

**Comment by askpatrickw** [comment]
Now what I see is it looks fine, but when an edit (remove) is made the menu looks all wonky, then I click done, refresh and can make another edit.

Its an acceptable workaround for me... just noting it in case someone else ends up here.
