### ISSUE TITLE
energy page top bar

### ISSUE THREAD

**Issue by tobyknobi** [th3jesta/ha-lcars#72]
If i go to the energy page (on left side bar), there is no skin on the top bar.

**Comment by th3jesta** [comment]
My ability to fix pages outside of dashboards is **extremely** limited, due to limitations in the mod `card-mod` on which this theme relies.

**Comment by tobyknobi** [comment]
Oké thanks. And many thanks for this mod. I really love it. And I am using it everyday.
Lcars is the best interface ever.

**Comment by th3jesta** [comment]
Glad you like it! Thank you for the very kind words.
