### ISSUE TITLE
Color Issue?

### ISSUE THREAD

**Issue by matellis** [th3jesta/ha-lcars#74]
The colors for LCARS 'default' don't match the default LCARS implementation. Have I done something wrong? See image comparing my current HA implentation of ha-lcars versus those for PiHole and SmokePing.

![Screenshot 2023-08-27 at 12 28 15 PM](https://github.com/th3jesta/ha-lcars/assets/138857/3d3a29d2-047a-4c83-ae9b-2ed60835a33e)

If this is simply an implementation decision, any pointers to where to put my own colors would be helpful. I looked in the code, and the base colors seem to be 'correct' as per https://www.thelcars.com so I'm not sure why they aren't showing up in my implementation. 

Thanks

**Comment by th3jesta** [comment]
The image on the left is showing the LCARS "Modern" color scheme. I suspect you have a conflict between what you are selecting as the backend theme and your profile theme. LCARS "Default" should look more like the Smoke Ping interface you have pictured (and also the hero images at the top of the HA_LCARS documentation). The PiHole colors look completely arbitrary to me (though not bad).
