### ISSUE TITLE
Way to line up opposing footers

### ISSUE THREAD

**Issue by smugleafdev** [th3jesta/ha-lcars#76]
This is a common occurence:

![Screenshot 2023-08-30 at 2 44 51 PM](https://github.com/th3jesta/ha-lcars/assets/20119855/136abd66-f779-4780-8699-675666284a54)

I would like a way to line these up perfectly.

Alternatively, being able to override HA's default card width would allow this just by having an extra wide view using "-contained" borders, and filling the two columns via horizontal stacks.

**Comment by smugleafdev** [comment]
That does work! Using the new Masonry (layout-card) and adding width: 800 into the text box does allow me to have one very wide LCARS themed card. Unfortunately for me, the cards I wanted to use are custom HACS cards that have problems like those in [issue 48](https://github.com/th3jesta/ha-lcars/issues/48), like so:

![image](https://github.com/th3jesta/ha-lcars/assets/20119855/74fb382c-a50a-4d60-a770-331a0c66d815)

Seems any custom HACS card gets funky.

**Comment by smugleafdev** [comment]
Alternatively, I was able to tweak it slightly to bump the height of the shorter footer:

```
    card_mod:
      class: footer
      style: |
        ha-card {
          font-size: 1.17em
        }
```

It lines up differently between devices (still a pixel off on desktop), but that's fine as I only cared about how it looks on my tablet.

**Comment by Daverover66** [comment]
I know this is marked as completed, but I have a different solution to line up opposing or indeed multiple footers in row of vertical stacks.  I use this method quite extensively on my tablet dashboard. Here's an example of such a line up
![Screenshot_20241013_185527_Home Assistant](https://github.com/user-attachments/assets/e1583a05-ec2e-4ddd-a9bd-8c81b38c34c2)

I used the following to change the card height until the footers align. You can apply this to individual entities in an entities card as well:

```yaml
  - type: custom:power-distribution-card
    card_mod:
      class: middle-left
      style: |
        ha-card {
          height: 368px !important;
        }
```
