### ISSUE TITLE
Clock in top right disappears with updates

### ISSUE THREAD

**Issue by SparkMike77** [th3jesta/ha-lcars#80]
Still have :

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

In configuration.yaml but clock no longer appears in latest update.

**Comment by th3jesta** [comment]
I am unable to reproduce with the latest version of HA. Can you check the syntax? It was pasted in here with bullets, so it's hard to tell if you have it formatted correctly.

**Comment by th3jesta** [comment]
Solved on Discord.

**Comment by bobdanek** [comment]
@th3jesta Can you please share the solution here?
