### ISSUE TITLE
HACS/Settings page colors

### ISSUE THREAD

**Issue by z3r0l1nk** [th3jesta/ha-lcars#81]
Hello all,
Is there any way to change the colors for the HACS/Settings pages?
The colors are a nightmare and burn my eyes, I tried to find a solution by myself but without success.

![image](https://github.com/th3jesta/ha-lcars/assets/31653632/d884deb7-fa24-410d-b989-d44e42a57438)

**Comment by 344Clinton** [comment]
I second this one. All the themes have grey text and is quite difficult to read. Even when I edit yaml code for the dashboard, It's grey on white.... yuk.

I found this 

  _primary-text-color: var(--lcars-text-gray)
  secondary-text-color: var(--lcars-text-gray)
  text-primary-color: var(--lcars-text-gray)_

in the lcars.yaml file but I wasn;t sure if I should change it and to what...

**Comment by th3jesta** [comment]
Related to #16

**Comment by th3jesta** [comment]
Implemented in 3.0
