### ISSUE TITLE
Design fail

### ISSUE THREAD

**Issue by FoxXxHater** [th3jesta/ha-lcars#84]
Hello everybody,

i want to ask how i, or the project itself, can change the color from the title named objects?

So in my case it looks so:
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/0b4ac2c6-17f2-4781-a820-87dd206b6ad9)

but i want to look is like lcars closer without the (white) fade...

Thanks for help...

**Comment by th3jesta** [comment]
If you followed [entities portion of the guide](https://github.com/th3jesta/ha-lcars#iv-create-the-entities) and created the entities, turning off `input_boolean.lcars_texture` will disable the white fade. To change the titles, you need to remove the title from your existing card and create a Markdown card to act as the title for the cards below. I recommend putting them all into a vertical stack card so they stay grouped together. Is German/Deutsch your native language?

**Comment by th3jesta** [comment]
It appears that you speak German (please forgive me if that is incorrect), so I attempted a Chat-GPT translation of the README. Please let me know if that helps and if it's reasonably accurate. https://github.com/th3jesta/ha-lcars/blob/master/README-DE.md

**Comment by FoxXxHater** [comment]
Yes i speak german. You too?

I think i installed it wrong. I mean its many beers along where i installed it, so i can bee posible that i followed the wrong tutorial...
I will reinstall it and check it again. Is there an deinstall manual?

**Comment by th3jesta** [comment]
Übersetzung bereitgestellt von Chat-GPT:
Ich kenne nur ein paar Wörter auf Deutsch :) Aber ich habe gerade die README für Sie mit Chat-GPT übersetzt:
https://github.com/th3jesta/ha-lcars/blob/master/README-DE.md

Es sollte keinen Grund zum Deinstallieren und Neuinstallieren geben. Ich schlage vor, einfach die Dokumentation zu lesen und Ihre Arbeit zu überprüfen.

**Comment by FoxXxHater** [comment]
Okay, i will do that...

**Comment by FoxXxHater** [comment]
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/c7a9a482-1377-49ce-bd91-23b9f6e9bd46)
So, i think it looks better, bot how can i fix this underline?

**Comment by th3jesta** [comment]
That gets tricky due to how card alignments are handled in Home Assistant. I've not solved that problem for myself, but some folks in the Discord server have used things like [Lovelace Layout Card](https://github.com/thomasloven/lovelace-layout-card) to great effect to line up the tops and bottoms of cards and stacks. I recommend joining the Discord and asking for help there. It's a great community 😃  🍻

**Comment by FoxXxHater** [comment]
Did you have a picture?

**Comment by th3jesta** [comment]
Sure, here's an image and the beginning of the conversation from which it came from: https://discord.com/channels/1059179538371858493/1059182416822030406/1114294065371021513
![image](https://github.com/th3jesta/ha-lcars/assets/38670315/78a5a69e-7e1b-44c1-9f65-2947347f67dc)

**Comment by FoxXxHater** [comment]
looks good

How you added the stardate? and how you created the nice floorplan? :XD

**Comment by th3jesta** [comment]
It's not mine. That's all from user lordpsycho on the the Discord channel. He created all of that, and explains it in Discord. He put a lot of work into it!

**Comment by th3jesta** [comment]
Sorry I missed it. I responded.
