### ISSUE TITLE
Home Assistant 2024.2.0 (SOLVE)

### ISSUE THREAD

**Issue by seamansrl** [th3jesta/ha-lcars#85]
Home Assistant 2024.2.0 (SOLVE)

With the Home Assistant 2024.2.0 update, the LCARS styles are broken, but don't worry, it is solved like this:

Only 2 changes in "/config/themes/lcars/lcars.yaml":

1) We search for "**item-text**" and change the value "**margin-right**" to "**10px**" so that it looks like this:

    .item-text {
      text-align: right;
      margin-left: auto;
      margin-right: 10px;
      margin-bottom: -23px;
      text-transform: uppercase;
    }

This fixes the navigation bar.

2) then we look for "**# Toolbar and dashboard modifications**" and write just above:

      ha-state-icon {
        max-height: 100% !important;
      }

This fixes the button icons.

Ready! with this everything resolved.

Download the fixed file:

https://1drv.ms/u/s!AhAX-nXNLZPIsbg2ApwoXHQW4r-ebQ?e=MjiGFl

Greetings

**Comment by seamansrl** [comment]
/config/themes/lcars/lcars.yaml
________________________________
De: FoxXxHater ***@***.***>
Enviado: jueves, 8 de febrero de 2024 10:22
Para: th3jesta/ha-lcars ***@***.***>
Cc: SeaMan SRL ***@***.***>; Author ***@***.***>
Asunto: Re: [th3jesta/ha-lcars] Home Assistant 2024.2.0 (SOLVE) (Issue #85)


In wich file you make the edits? In the lcars.yml?

**Comment by seamansrl** [comment]
________________________________
De: Fernando P. Maniglia ***@***.***>
Enviado: jueves, 8 de febrero de 2024 10:24
Para: th3jesta/ha-lcars ***@***.***>
Asunto: RE: [th3jesta/ha-lcars] Home Assistant 2024.2.0 (SOLVE) (Issue #85)

/config/themes/lcars/lcars.yaml
________________________________
De: FoxXxHater ***@***.***>
Enviado: jueves, 8 de febrero de 2024 10:22
Para: th3jesta/ha-lcars ***@***.***>
Cc: SeaMan SRL ***@***.***>; Author ***@***.***>
Asunto: Re: [th3jesta/ha-lcars] Home Assistant 2024.2.0 (SOLVE) (Issue #85)


In wich file you make the edits? In the lcars.yml?

**Comment by FoxXxHater** [comment]
Thx

**Comment by MichelJourdain** [comment]
This solution works well for displaying the icons section, but there is a difference in the color of the icons.

Avant: 

![IMG_8557](https://github.com/th3jesta/ha-lcars/assets/83040228/56559c3c-9da6-46fa-9f47-690b5d971290)

Après:

![IMG_8556](https://github.com/th3jesta/ha-lcars/assets/83040228/d39ba0f1-e841-40d4-992c-1a17b47cfcd6)
