### ISSUE TITLE
Deprecation warning "The `beat` Time & Date sensor is being removed" - LCARS affected?

### ISSUE THREAD

**Issue by jshatch** [th3jesta/ha-lcars#86]
I noticed this message today regarding the "beat" sensor being removed.  I only have it enabled because I installed the LCARS theme and it is mentioned in the install docs that the clock requires it.  This is more of an FYI than anything, if I have to not use the clock that's fine.

![image](https://github.com/th3jesta/ha-lcars/assets/12240115/def6a40d-db67-4094-a186-94575cccdd4d)

**Comment by jshatch** [comment]
The only other mention I've seen about this is here: https://github.com/home-assistant/core/issues/109922

**Comment by th3jesta** [comment]
Removed this from the readmes. Thanks!
