### ISSUE TITLE
Bug after Update to 02.24

### ISSUE THREAD

**Issue by FoxXxHater** [th3jesta/ha-lcars#87]
Hello, 

after i update to the latest version i have this bug. 
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/de993a43-ac41-4dff-a836-10fa7c4626a3)

How can i fix it?

**Comment by z3r0l1nk** [comment]
same issues here and the text has shifted to much in the right for the menu.
Also, how do I remove the clock from right upper corner?

![image](https://github.com/th3jesta/ha-lcars/assets/31653632/2d8995e3-5a9a-445f-9820-1a3cac7d9084)

**Comment by FoxXxHater** [comment]
> same issues here and the text has shifted to much in the right for the menu. fixing my issue is in lcars.yaml .item-text { text-align: right; margin-left: auto; margin-right: 0px; margin-bottom: -23px; text-transform: uppercase;
> 
> edit margin-right from -12px to 0px
> 
> ![image](https://private-user-images.githubusercontent.com/31653632/303310723-2d8995e3-5a9a-445f-9820-1a3cac7d9084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTI5OTUsIm5iZiI6MTcwNzM5MjY5NSwicGF0aCI6Ii8zMTY1MzYzMi8zMDMzMTA3MjMtMmQ4OTk1ZTMtNWE5YS00NDVmLTk4MjAtMWEzY2FjN2Q5MDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDExNDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NTYxYmI3OWZmMDRkNWM3MmE0NzM1MmIxOTRkZWQ0NGM2OThhMWQ2ZDYzMjEwODAzOGFiN2U5YWZhNzVlMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kjQL4IDT5YNqCKPhdwPYD_jY9U1JPOqGRVv_IBgWdbM)

Same here....
![image](https://github.com/th3jesta/ha-lcars/assets/54017453/16efa782-a3c9-4eb7-81f4-86bb6345f2dc)


I will try this soon

**Comment by z3r0l1nk** [comment]
So found in the issue list the solution already by someone else and works, first one is different then mine, but the second one also works.
https://github.com/th3jesta/ha-lcars/issues/85

**Comment by seamansrl** [comment]
I Just Fix that:

See:
https://github.com/th3jesta/ha-lcars/issues/85

**Comment by seamansrl** [comment]
> ![Screenshot 2024-02-08 132912](https://private-user-images.githubusercontent.com/142350143/303345383-4e368458-eda3-4e25-874e-b14a18fc9cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTk1MjEsIm5iZiI6MTcwNzM5OTIyMSwicGF0aCI6Ii8xNDIzNTAxNDMvMzAzMzQ1MzgzLTRlMzY4NDU4LWVkYTMtNGUyNS04NzRlLWIxNGExOGZjOWNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMzMzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjUzNWU4OGJiZjFiZDc2YTYyYWYyYjJjMGJlMWViMjUxZDFiM2QxODUyOWI4ZWM0YzBjMWNhNDNmY2VhZjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KhMyLMe-b_JsFmA2e_sFNyBvCea5SnF5tiEgbcPEnxI)
> 
> Whilst following that link has fixed the icons, they now do not show their current status off/on as they previously did?

![Captura de pantalla 2024-02-08 103242](https://github.com/th3jesta/ha-lcars/assets/28654280/d4efdd19-0c2f-47ab-ae9a-dfc634e9e81e)

**Comment by seamansrl** [comment]
It works well for me. I just uploaded my file with corrections and improvements to OneDrive and left the link in the post https://github.com/th3jesta/ha-lcars/issues/85

**Comment by sgofferj** [comment]
The published fix in #85 only fixes the spacing of buttons and icons for me. Icons are NOT colored by state anymore and the clock is covering the functions top right...

![Screenshot_20240208_162125](https://github.com/th3jesta/ha-lcars/assets/3258466/e6b7c8c6-2723-4c1a-bedc-4b3a687e1ced)

**Comment by seamansrl** [comment]
> The published fix in #85 only fixes the spacing of buttons and icons for me. Icons are NOT colored by state anymore and the clock is covering the functions top right...
> 
> 
> 
> ![Screenshot_20240208_162125](https://github.com/th3jesta/ha-lcars/assets/3258466/e6b7c8c6-2723-4c1a-bedc-4b3a687e1ced)
> 
> 

Make a backup of your yaml file and replace it with the one I left on OneDrive. don't leave both in themes folder or there could be weird crashes. Everything works correctly for me.

![image](https://github.com/th3jesta/ha-lcars/assets/28654280/53cf4ed1-8cbe-48f5-8ec9-03759bfa2193)

**Comment by sgofferj** [comment]
@seamansrl 
Status color works now correctly but the clock is gone completely...

**Comment by seamansrl** [comment]
> @seamansrl Status color works now correctly but the clock is gone completely...

Yes, I should have removed the watch because it worked well on the PC but poorly on the SmartPhone. I couldn't find a way to make it stable, it always ended up crashing at some point.

**Comment by th3jesta** [comment]
@seamansrl I'm working on fixes now, and almost done. What did you do to fix the icons? I am not sure where to look to find your fix.

**Comment by seamansrl** [comment]
> @seamansrl I'm working on fixes now, and almost done. What did you do to fix the icons? I am not sure where to look to find your fix.

only insert that:

ha-state-icon {
max-height: 100% !important;
}

**Comment by th3jesta** [comment]
Sorry, I meant icon colors. I already had a fix for that. But I found a fix for it. Thanks! 
Update dropping in minutes.

**Comment by seamansrl** [comment]
> Sorry, I meant icon colors. I already had a fix for that. But I found a fix for it. Thanks!
> Update dropping in minutes.

excellent!

**Comment by th3jesta** [comment]
2.2.3 has been released with compatibility for Home Assistant 2024.2. Sorry for the delay in getting this fixed. It took a lot of work to fix things with the most minimal impact. Don't forget to back up your custom theme colors!
