### ISSUE TITLE
Navigation Scrollbar appearing over sidebar text

### ISSUE THREAD

**Issue by infered5** [th3jesta/ha-lcars#94]
![image](https://github.com/th3jesta/ha-lcars/assets/14192695/8991ce96-36a8-4598-a7c8-85205a1699f2)

Core: 2024.4.1
Supervisor: 2024.03.1
OS: 12.1
Frontend: 20240404.1
HA-LCARS 2.2.4

Other themes that sticky their text on the left side do not show this issue, but possibly would have been affected if they stickied their text to the right side.

![image](https://github.com/th3jesta/ha-lcars/assets/14192695/4177ce64-2bc0-4aa7-90a8-36b6446df8de)

**Comment by th3jesta** [comment]
I added a fix that's available in the latest release 2.2.5. Please update and let me know if that fixes it for you. I'm not sure if it will or not because your scrollbars look different than mine.
