### ISSUE TITLE
Prerequisite "II. Add the font and JavaScript file" doesn't seem to line up with HA interface

### ISSUE THREAD

**Issue by TheGorf** [th3jesta/ha-lcars#97]
The call-out for Prereq II. Add the font and JavaScript file. Your documentation calls out some steps that don't seem to exist in the version of HA that I am running. So I'm just doing the manual download method. I can download the .js file per your instructions, but I'm not quite clear on what to do with the stylesheet. Should it just be downloaded into the same directory?

**Comment by jszmajda** [comment]
I'm having the same problem, would love any recommendations on how to proceed :)

**Comment by jszmajda** [comment]
Ah - I figured it out - in my profile, I had to enable "Advanced mode" under User Settings. That revealed the 3-dot menu and allowed me to add the Resources. Hope that helps!
